vendor: BoCloud
name: BoCloud BeyondContainer
version: v1.17
website_url: http://bocloud.com.cn/product/BeyondContainer
documentation_url: http://bocloud.com.cn/product/BeyondContainer
product_logo_url: http://www.bocloud.com.cn/manager/images/by_logo.png
